name: Add latest tag to new release
on:
  release:
    types: [published] # This makes it run only when a new released is published

jobs: 
  run:
    name: Add/update tag to new release
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        description: Latest tag pointing to latest version
        tag-name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Leave this line unchanged