name: Release Generator

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: gem install nokogiri
    - name: Run generator
      run: |
        ruby parse.rb
        wget http://download.geofabrik.de/europe/romania-latest.osm.bz2
        bzip2 -d romania-latest.osm.bz2 
        docker run --rm -v ${PWD}:/workdir opentransport/pfaedle pfaedle -D -d /workdir/gtfs-out -o /workdir/gtfs-processed --write-trgraph --write-graph --write-cgraph -mall -x /workdir/romania-latest.osm /workdir/gtfs-out
        zip -rj gtfs-cfr.zip gtfs-processed
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        name: Release ${{ steps.date.outputs.date }}
        body: Updating to the lastet version of data provided by cfr
        draft: false
        prerelease: false
        files: |
            gtfs-cfr.zip
            gtfs-out/graph.json
            gtfs-out/trgraph-rail.json

